# Generated by Django 2.0.5 on 2018-06-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=500)),
                ('userAge', models.CharField(max_length=3)),
                ('dateJoined', models.CharField(max_length=10)),
                ('bio', models.CharField(max_length=280)),
                ('avi', models.CharField(max_length=1000)),
            ],
        ),
    ]
